export type Country = { code: string; nombre: string };

// Lista de países (código ISO 3166-1 alpha-2 + nombre en español) para el
// selector de envío internacional del checkout de café. Colombia va primero
// porque es el destino más común; el resto en orden alfabético.
export const countries: Country[] = [
  { code: "CO", nombre: "Colombia" },
  { code: "AR", nombre: "Argentina" },
  { code: "AU", nombre: "Australia" },
  { code: "AT", nombre: "Austria" },
  { code: "BE", nombre: "Bélgica" },
  { code: "BO", nombre: "Bolivia" },
  { code: "BR", nombre: "Brasil" },
  { code: "CA", nombre: "Canadá" },
  { code: "CL", nombre: "Chile" },
  { code: "CN", nombre: "China" },
  { code: "CR", nombre: "Costa Rica" },
  { code: "DK", nombre: "Dinamarca" },
  { code: "EC", nombre: "Ecuador" },
  { code: "SV", nombre: "El Salvador" },
  { code: "ES", nombre: "España" },
  { code: "US", nombre: "Estados Unidos" },
  { code: "FI", nombre: "Finlandia" },
  { code: "FR", nombre: "Francia" },
  { code: "DE", nombre: "Alemania" },
  { code: "GR", nombre: "Grecia" },
  { code: "GT", nombre: "Guatemala" },
  { code: "HN", nombre: "Honduras" },
  { code: "IN", nombre: "India" },
  { code: "IE", nombre: "Irlanda" },
  { code: "IT", nombre: "Italia" },
  { code: "JP", nombre: "Japón" },
  { code: "MX", nombre: "México" },
  { code: "NL", nombre: "Países Bajos" },
  { code: "NZ", nombre: "Nueva Zelanda" },
  { code: "NI", nombre: "Nicaragua" },
  { code: "NO", nombre: "Noruega" },
  { code: "PA", nombre: "Panamá" },
  { code: "PY", nombre: "Paraguay" },
  { code: "PE", nombre: "Perú" },
  { code: "PL", nombre: "Polonia" },
  { code: "PT", nombre: "Portugal" },
  { code: "PR", nombre: "Puerto Rico" },
  { code: "GB", nombre: "Reino Unido" },
  { code: "DO", nombre: "República Dominicana" },
  { code: "SE", nombre: "Suecia" },
  { code: "CH", nombre: "Suiza" },
  { code: "UY", nombre: "Uruguay" },
  { code: "VE", nombre: "Venezuela" },
];
